use_frameworks!

platform :ios, '12.0'

target 'testpod_Example' do
  pod 'testpody', :path => '../'

  target 'testpod_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
#            config.build_settings["DEVELOPMENT_TEAM"] = "J5MCF6VR6V"
            config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
         end
    end
  end
end
